from django.urls import path

from .views import (
    AnnouncementDetailView,
    AnnouncementFeedView,
    CalendarEventDetailView,
    CalendarEventListView,
    CurrentUserProfileView,
    CurrentUserView,
    DashboardView,
    DivisionCalendarEventListCreateView,
    DivisionDocumentListCreateView,
    DivisionInvitationCreateView,
    DivisionListCreateView,
    InvitationAcceptView,
    LoginView,
    NotificationDetailView,
    NotificationListView,
    NotificationMarkAllReadView,
    OrganizationAnnouncementListCreateView,
    OrganizationCalendarEventListCreateView,
    OrganizationDocumentListCreateView,
    OrganizationInvitationCreateView,
    OrganizationListCreateView,
    ProjectDocumentListCreateView,
    ProjectCalendarEventListCreateView,
    ProjectInvitationCreateView,
    ProjectListCreateView,
    RegisterView,
    ResourceDocumentDetailView,
    ResourceDocumentDownloadView,
    TaskDetailView,
    TaskListCreateView,
)


urlpatterns = [
    path("auth/register/", RegisterView.as_view(), name="register"),
    path("auth/login/", LoginView.as_view(), name="login"),
    path("auth/me/", CurrentUserView.as_view(), name="current_user"),
    path("auth/profile/", CurrentUserProfileView.as_view(), name="current_user_profile"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("calendar/events/", CalendarEventListView.as_view(), name="calendar_event_list"),
    path(
        "calendar/events/<int:pk>/",
        CalendarEventDetailView.as_view(),
        name="calendar_event_detail",
    ),
    path("organizations/", OrganizationListCreateView.as_view(), name="organization_list"),
    path(
        "organizations/<int:pk>/invite/",
        OrganizationInvitationCreateView.as_view(),
        name="organization_invite",
    ),
    path(
        "organizations/<int:pk>/documents/",
        OrganizationDocumentListCreateView.as_view(),
        name="organization_documents",
    ),
    path(
        "organizations/<int:pk>/announcements/",
        OrganizationAnnouncementListCreateView.as_view(),
        name="organization_announcements",
    ),
    path(
        "organizations/<int:pk>/calendar/events/",
        OrganizationCalendarEventListCreateView.as_view(),
        name="organization_calendar_events",
    ),
    path("divisions/", DivisionListCreateView.as_view(), name="division_list"),
    path(
        "divisions/<int:pk>/invite/",
        DivisionInvitationCreateView.as_view(),
        name="division_invite",
    ),
    path(
        "divisions/<int:pk>/documents/",
        DivisionDocumentListCreateView.as_view(),
        name="division_documents",
    ),
    path(
        "divisions/<int:pk>/calendar/events/",
        DivisionCalendarEventListCreateView.as_view(),
        name="division_calendar_events",
    ),
    path("projects/", ProjectListCreateView.as_view(), name="project_list"),
    path(
        "projects/<int:pk>/invite/",
        ProjectInvitationCreateView.as_view(),
        name="project_invite",
    ),
    path(
        "projects/<int:pk>/documents/",
        ProjectDocumentListCreateView.as_view(),
        name="project_documents",
    ),
    path(
        "projects/<int:pk>/calendar/events/",
        ProjectCalendarEventListCreateView.as_view(),
        name="project_calendar_events",
    ),
    path("documents/<int:pk>/", ResourceDocumentDetailView.as_view(), name="document_detail"),
    path(
        "documents/<int:pk>/download/",
        ResourceDocumentDownloadView.as_view(),
        name="document_download",
    ),
    path("tasks/", TaskListCreateView.as_view(), name="task_list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task_detail"),
    path("notifications/", NotificationListView.as_view(), name="notification_list"),
    path(
        "notifications/mark-all-read/",
        NotificationMarkAllReadView.as_view(),
        name="notification_mark_all_read",
    ),
    path(
        "notifications/<int:pk>/",
        NotificationDetailView.as_view(),
        name="notification_detail",
    ),
    path("announcements/", AnnouncementFeedView.as_view(), name="announcement_feed"),
    path(
        "announcements/<int:pk>/",
        AnnouncementDetailView.as_view(),
        name="announcement_detail",
    ),
    path("invitations/accept/", InvitationAcceptView.as_view(), name="invitation_accept"),
]
